spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/2022212950?createDatabaseIfNotExist=true'
    username: 2022212950
    password: 2022212950

  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
    org:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'